version: '3.3'



services:
  mysql:
    image: mysql:latest
    #    platform: linux/amd64 # uncomment this if using Apple silicon
    hostname: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: timeSheetDevOps

    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql:db
    ports:
      - "3308:80"
  timesheetapp:
    build: ./
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - WAIT_HOSTS=mysql:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
      #- DEFAULT_PATH=<Target path in windows>
    depends_on:
      - mysql
      - phpmyadmin
volumes:
  db_data: